### ISSUE TITLE
多账号运行报错

### ISSUE THREAD

**Issue by YatsukiRenka** [Womsxd/AutoMihoyoBBS#115]
- 系统：Ubuntu 20.04.4 LTS
- Python 版本：Python 3.8.10
- 出错过程：
    1 `pip3 install -r requirement.txt`
    2 在 `/config` 里面添加了三个账号的 `json` 文件并填入 `cookie`
    3 修改了 `json` 中所需要签到的游戏为 `true`
    4 使用 `python3 main_multi.py` 运行
- Console log：
```bash
2022-05-09T10:59:15 INFO AutoMihoyoBBS Multi User mode
2022-05-09T10:59:15 INFO 正在搜索配置文件！
2022-05-09T10:59:15 INFO 已搜索到3个配置文件，请确认是否无多余文件！
['guofu.json', 'beta.json', 'genshin.json']
请输入回车继续，需要重新搜索配置文件请Ctrl+C退出脚本
2022-05-09T10:59:21 INFO 正在执行guofu.json
2022-05-09T10:59:21 INFO Config加载完毕
2022-05-09T10:59:23 INFO 登录成功！
2022-05-09T10:59:23 INFO 正在保存Config！
2022-05-09T10:59:23 INFO Config保存完毕
2022-05-09T10:59:27 INFO 正在获取任务列表
2022-05-09T10:59:28 INFO 新的一天，今天可以获得90个米游币
2022-05-09T10:59:28 INFO 正在获取帖子列表......
2022-05-09T10:59:28 INFO 已获取5个帖子
2022-05-09T10:59:28 INFO 正在签到......
2022-05-09T10:59:29 INFO 原神OK
2022-05-09T10:59:36 INFO 大别野OK
2022-05-09T10:59:44 INFO 正在看帖......
2022-05-09T11:00:04 INFO 正在点赞......
2022-05-09T11:01:10 INFO 正在执行分享任务......
2022-05-09T11:01:11 INFO 分享任务执行成功......
2022-05-09T11:01:18 INFO 正在获取任务列表
2022-05-09T11:01:19 INFO 似乎还有任务没完成，今天还能获得30
2022-05-09T11:01:19 INFO 正在获取帖子列表......
2022-05-09T11:01:19 INFO 已获取5个帖子
2022-05-09T11:01:19 INFO 讨论区任务已经完成过了~
2022-05-09T11:01:19 INFO 看帖任务已经完成过了~
2022-05-09T11:01:19 INFO 正在点赞......
2022-05-09T11:02:18 INFO 分享任务已经完成过了~
2022-05-09T11:02:18 INFO 正在获取任务列表
2022-05-09T11:02:18 INFO 似乎还有任务没完成，今天还能获得30
2022-05-09T11:02:18 INFO 正在获取帖子列表......
2022-05-09T11:02:18 INFO 已获取5个帖子
2022-05-09T11:02:18 INFO 讨论区任务已经完成过了~
2022-05-09T11:02:18 INFO 看帖任务已经完成过了~
2022-05-09T11:02:18 INFO 正在点赞......
2022-05-09T11:03:24 INFO 分享任务已经完成过了~
2022-05-09T11:03:24 INFO 正在获取任务列表
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1114: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:1114: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_multi.py", line 71, in <module>
    main_multi(autorun)
  File "main_multi.py", line 43, in main_multi
    run_code, run_message = main.main()
  File "/root/mihoyo/AutoMihoyoBBS/main.py", line 60, in main
    bbs.get_tasks_list()
  File "/root/mihoyo/AutoMihoyoBBS/mihoyobbs.py", line 55, in get_tasks_list
    req = http.get(url=setting.bbs_Tasks_list, headers=self.headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1025, in get
    return self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1114: The handshake operation timed out
```

**Comment by Womsxd** [comment]
timeout，连接 超时了，试试重试

**Comment by YatsukiRenka** [comment]
手机登上去看了一下，这个账号未绑定手机导致点不了赞，可能因为多次重试超时了，关了点赞功能之后没问题了，感谢回复
