### ISSUE TITLE
本地运行时报错

### ISSUE THREAD

**Issue by windskyxb** [Womsxd/AutoMihoyoBBS#126]
C:\Users\winds\Documents\Codes\AutoMihoyoBBS>python main.py
Traceback (most recent call last):
  File "C:\Users\winds\Documents\Codes\AutoMihoyoBBS\main.py", line 97, in <module>
    status_code, message = main()
  File "C:\Users\winds\Documents\Codes\AutoMihoyoBBS\main.py", line 18, in main
    config.load_config()
  File "C:\Users\winds\Documents\Codes\AutoMihoyoBBS\config.py", line 66, in load_config
    data = json.load(f)
  File "C:\Users\winds\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\winds\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\winds\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\winds\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 22 column 9 (char 918)

**Comment by windskyxb** [comment]
发现错误在哪了，配置文件中使用了中文逗号,,ԾㅂԾ,,

**Comment by windskyxb** [comment]
发现错误了，配置文件中使用了中文逗号,,ԾㅂԾ,,
