### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by MoXiaoXi233** [Womsxd/AutoMihoyoBBS#133]
2022-06-15T02:46:22 INFO 正在为旅行者墨希Moxiify进行签到...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 52, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 49, in start_tls
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 71, in <module>
    main_multi(autorun)
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 43, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 85, in main
    return_data += "\n\n" + genshin_help.sign_account()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/genshin.py", line 55, in sign_account
    is_data = self.is_sign(region=i[2], uid=i[1])
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/genshin.py", line 36, in is_sign
    req = http.get(setting.genshin_Is_signurl.format(setting.genshin_Act_id, region, uid), headers=self.headers)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1039, in get
    return self.request(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out

## 执行结束... 2022-06-15 02:46:41 耗时 25 秒

**Comment by MoXiaoXi233** [comment]
已解决，将预设的等待10s改成30s

**Comment by Womsxd** [comment]
境外机子吗？还是国内

**Comment by MoXiaoXi233** [comment]
香港奥，我感觉是米哈游服务器的锅，这边把等待时间调大就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Womsxd/AutoMihoyoBBS] 报错 (Issue #133)





 
境外机子吗？还是国内
