### ISSUE TITLE
最近几天某个报错

### ISSUE THREAD

**Issue by QiE2035** [Womsxd/AutoMihoyoBBS#140]
```
2022-06-30T04:14:22.7850693Z 2022-06-30T04:14:22 INFO Config加载完毕
2022-06-30T04:14:22.7853468Z 2022-06-30T04:14:22 INFO 正在获取任务列表
2022-06-30T04:14:24.0106686Z 2022-06-30T04:14:24 INFO 似乎还有任务没完成，今天还能获得60
2022-06-30T04:14:24.0107097Z 2022-06-30T04:14:24 INFO 正在获取帖子列表......
2022-06-30T04:14:24.5436067Z 2022-06-30T04:14:24 INFO 已获取5个帖子
2022-06-30T04:14:24.5436543Z 2022-06-30T04:14:24 INFO 讨论区任务已经完成过了~
2022-06-30T04:14:24.5436918Z 2022-06-30T04:14:24 INFO 正在看帖......
2022-06-30T04:14:31.8373724Z 2022-06-30T04:14:31 INFO 正在点赞......
2022-06-30T04:14:42.3024875Z Traceback (most recent call last):
2022-06-30T04:14:42.3034764Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
2022-06-30T04:14:42.3035607Z     yield
2022-06-30T04:14:42.3036535Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/backends/sync.py", line 57, in start_tls
2022-06-30T04:14:42.3037062Z     raise exc
2022-06-30T04:14:42.3037807Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/backends/sync.py", line 52, in start_tls
2022-06-30T04:14:42.3038699Z     sock = ssl_context.wrap_socket(
2022-06-30T04:14:42.3039229Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/ssl.py", line 501, in wrap_socket
2022-06-30T04:14:42.3166827Z     return self.sslsocket_class._create(
2022-06-30T04:14:42.3168117Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/ssl.py", line 1041, in _create
2022-06-30T04:14:42.3170741Z     self.do_handshake()
2022-06-30T04:14:42.3171130Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/ssl.py", line 1310, in do_handshake
2022-06-30T04:14:42.3181237Z     self._sslobj.do_handshake()
2022-06-30T04:14:42.3181686Z socket.timeout: _ssl.c:1112: The handshake operation timed out
2022-06-30T04:14:42.3181917Z 
2022-06-30T04:14:42.3182122Z During handling of the above exception, another exception occurred:
2022-06-30T04:14:42.3182361Z 
2022-06-30T04:14:42.3182496Z Traceback (most recent call last):
2022-06-30T04:14:42.3183373Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2022-06-30T04:14:42.3183954Z     yield
2022-06-30T04:14:42.3184588Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
2022-06-30T04:14:42.3185057Z     resp = self._pool.handle_request(req)
2022-06-30T04:14:42.3185786Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
2022-06-30T04:14:42.3186211Z     raise exc
2022-06-30T04:14:42.3186855Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
2022-06-30T04:14:42.3187330Z     response = connection.handle_request(request)
2022-06-30T04:14:42.3188017Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
2022-06-30T04:14:42.3188426Z     raise exc
2022-06-30T04:14:42.3189646Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
2022-06-30T04:14:42.3190090Z     stream = self._connect(request)
2022-06-30T04:14:42.3190728Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 150, in _connect
2022-06-30T04:14:42.3191417Z     stream = stream.start_tls(**kwargs)
2022-06-30T04:14:42.3192089Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/backends/sync.py", line 57, in start_tls
2022-06-30T04:14:42.3192483Z     raise exc
2022-06-30T04:14:42.3192888Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/contextlib.py", line 137, in __exit__
2022-06-30T04:14:42.3229892Z     self.gen.throw(typ, value, traceback)
2022-06-30T04:14:42.3230720Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
2022-06-30T04:14:42.3231148Z     raise to_exc(exc)
2022-06-30T04:14:42.3231515Z httpcore.ConnectTimeout: _ssl.c:1112: The handshake operation timed out
2022-06-30T04:14:42.3231764Z 
2022-06-30T04:14:42.3231965Z The above exception was the direct cause of the following exception:
2022-06-30T04:14:42.3232201Z 
2022-06-30T04:14:42.3232340Z Traceback (most recent call last):
2022-06-30T04:14:42.3232819Z   File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 97, in <module>
2022-06-30T04:14:42.3233233Z     status_code, message = main()
2022-06-30T04:14:42.3233684Z   File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 57, in main
2022-06-30T04:14:42.3234070Z     bbs.like_posts()
2022-06-30T04:14:42.3234515Z   File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/mihoyobbs.py", line 156, in like_posts
2022-06-30T04:14:42.3235000Z     req = http.post(url=setting.bbs_Like_url, headers=self.headers,
2022-06-30T04:14:42.3235659Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 1130, in post
2022-06-30T04:14:42.3236237Z     return self.request(
2022-06-30T04:14:42.3236844Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 815, in request
2022-06-30T04:14:42.3237338Z     return self.send(request, auth=auth, follow_redirects=follow_redirects)
2022-06-30T04:14:42.3237995Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 902, in send
2022-06-30T04:14:42.3238420Z     response = self._send_handling_auth(
2022-06-30T04:14:42.3239117Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 930, in _send_handling_auth
2022-06-30T04:14:42.3239570Z     response = self._send_handling_redirects(
2022-06-30T04:14:42.3240245Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
2022-06-30T04:14:42.3240708Z     response = self._send_single_request(request)
2022-06-30T04:14:42.3241385Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_client.py", line 1003, in _send_single_request
2022-06-30T04:14:42.3241846Z     response = transport.handle_request(request)
2022-06-30T04:14:42.3242521Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
2022-06-30T04:14:42.3242974Z     resp = self._pool.handle_request(req)
2022-06-30T04:14:42.3243431Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/contextlib.py", line 137, in __exit__
2022-06-30T04:14:42.3243828Z     self.gen.throw(typ, value, traceback)
2022-06-30T04:14:42.3244537Z   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2022-06-30T04:14:42.3245025Z     raise mapped_exc(message) from exc
2022-06-30T04:14:42.3245402Z httpx.ConnectTimeout: _ssl.c:1112: The handshake operation timed out
2022-06-30T04:14:42.3507992Z ##[error]Process completed with exit code 1.
```

**Comment by Womsxd** [comment]
时间超时了，服务器是在境外麻？

**Comment by kaximiss** [comment]
上海服务器也出现了相同的问题

**Comment by Womsxd** [comment]
???家宽还是服务器，还是云函数之类的环境
我挂脚本的腾讯云机子还没出现过这种情况

**Comment by MXZHT** [comment]
上海的一样的问题阿里云

**Comment by 2106653531** [comment]
腾讯云函数广州地区同样的报错

**Comment by QiE2035** [comment]
> 时间超时了，服务器是在境外麻？

GitHub Actions:

https://github.com/QiE2035/AutoMihoyoBBS_Runner

**Comment by Womsxd** [comment]
> > 时间超时了，服务器是在境外麻？
> 
> GitHub Actions:
> 
> https://github.com/QiE2035/AutoMihoyoBBS_Runner

估计是境外Ip的关系吧，mhy的bbs-api.mihoyo.com和api-takumi.mihoyo.com我在[在线ping](https://ping.chinaz.com/)这里的到的结果都是广州阿里云，没有cdn

**Comment by kaixinhacker** [comment]
像这种情况要怎么解决呢
