### ISSUE TITLE
代理软件与本程序httpx似乎有冲突

### ISSUE THREAD

**Issue by davidelectricfree** [Womsxd/AutoMihoyoBBS#15]
代理软件v2ray，在对极个别网站才开代理，所有流量都走direct的情况下（MIHOYO的网站也是走的直连模式），只要开了代理，该程序就无法使用，只要关了代理才可使用，因为服务器上有个另外的程序必须走代理，所以看作者大大是否能解决此问题。

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 227, in _tunnel_request
    ) = proxy_connection.handle_request(
  File "C:\Python39\lib\site-packages\httpcore\_sync\connection.py", line 136, in handle_request
    self.socket = self._open_socket(timeout)
  File "C:\Python39\lib\site-packages\httpcore\_sync\connection.py", line 163, in _open_socket
    return self._backend.open_tcp_stream(
  File "C:\Python39\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\Python39\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 127, in handle_request
    return self._tunnel_request(
  File "C:\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 256, in _tunnel_request
    raise ProxyError(exc)
httpcore.ProxyError: EOF occurred in violation of protocol (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\xx\文档\AutoMihoyoBBS\main.py", line 120, in <module>
    main()
  File "C:\Users\Administrator\xx\文档\AutoMihoyoBBS\main.py", line 45, in main
    bbs = mihoyobbs.mihoyobbs()
  File "C:\Users\Administrator\xx\文档\AutoMihoyoBBS\mihoyobbs.py", line 36, in __init__
    self.Get_taskslist()
  File "C:\Users\Administrator\xx\文档\AutoMihoyoBBS\mihoyobbs.py", line 49, in Get_taskslist
    req = http.get(url=setting.bbs_Taskslist, headers=self.headers)
  File "C:\Python39\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "C:\Python39\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Python39\lib\site-packages\httpx\_client.py", line 787, in request
    return self.send(
  File "C:\Python39\lib\site-packages\httpx\_client.py", line 878, in send
    response = self._send_handling_auth(
  File "C:\Python39\lib\site-packages\httpx\_client.py", line 908, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Python39\lib\site-packages\httpx\_client.py", line 947, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Python39\lib\site-packages\httpx\_client.py", line 983, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "C:\Python39\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python39\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ProxyError: EOF occurred in violation of protocol (_ssl.c:1129)

**Comment by Womsxd** [comment]
可以考虑卸载httpx，脚本会切到requests

**Comment by davidelectricfree** [comment]
> 可以考虑卸载httpx，脚本会切到requests

代码需要更改吗

**Comment by Womsxd** [comment]
> > 可以考虑卸载httpx，脚本会切到requests
> 
> 代码需要更改吗

不需要，我提前写了无httpx自动切requests

**Comment by Womsxd** [comment]
httpx是程序依赖的http请求库的其中一个
https://github.com/encode/httpx
可以尝试向上游提交报错
