### ISSUE TITLE
docker 运行报错

### ISSUE THREAD

**Issue by MrLv0816** [Womsxd/AutoMihoyoBBS#193]
`automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO 使用DOCKER运行米游社签到
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO Starting signing
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO AutoMihoyoBBS Multi User mode
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO 正在搜索配置文件！
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO 已搜索到1个配置文件，正在开始执行！
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO 正在执行config.json
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO Config加载完毕
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:14 INFO 正在获取任务列表
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO 新的一天，今天可以获得90个米游币
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO 正在获取帖子列表......
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO 已获取5个帖子
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO 正在签到......
automihoyobbs-master-mihoyo-bbs-1  | Traceback (most recent call last):
automihoyobbs-master-mihoyo-bbs-1  |   File "/var/app/./main_multi.py", line 71, in <module>
automihoyobbs-master-mihoyo-bbs-1  |     main_multi(autorun)
automihoyobbs-master-mihoyo-bbs-1  |   File "/var/app/./main_multi.py", line 43, in main_multi
automihoyobbs-master-mihoyo-bbs-1  |     run_code, run_message = main.main()
automihoyobbs-master-mihoyo-bbs-1  |   File "/var/app/main.py", line 54, in main
automihoyobbs-master-mihoyo-bbs-1  |     bbs.signing()
automihoyobbs-master-mihoyo-bbs-1  |   File "/var/app/mihoyobbs.py", line 127, in signing
automihoyobbs-master-mihoyo-bbs-1  |     data = req.json()
automihoyobbs-master-mihoyo-bbs-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
automihoyobbs-master-mihoyo-bbs-1  |     return jsonlib.loads(self.text, **kwargs)
automihoyobbs-master-mihoyo-bbs-1  |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
automihoyobbs-master-mihoyo-bbs-1  |     return _default_decoder.decode(s)
automihoyobbs-master-mihoyo-bbs-1  |   File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
automihoyobbs-master-mihoyo-bbs-1  |     raise JSONDecodeError("Extra data", s, end)
automihoyobbs-master-mihoyo-bbs-1  | json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO Current running datetime: 2022-08-19 21:16:15
automihoyobbs-master-mihoyo-bbs-1  | 2022-08-19T21:16:15 INFO Next run datetime: 2022-08-20 07:30:06
`

**Comment by MrLv0816** [comment]
![image](https://user-images.githubusercontent.com/46812909/185627114-58243b2e-96ef-4d97-8c6b-9783e43df42a.png)
