### ISSUE TITLE
运行脚本异常

### ISSUE THREAD

**Issue by needquit** [Womsxd/AutoMihoyoBBS#205]
## 开始执行... 2022-08-22 00:35:26

2022-08-22T00:35:27 INFO AutoMihoyoBBS Multi User mode
2022-08-22T00:35:27 INFO 正在搜索配置文件！
2022-08-22T00:35:27 INFO 已搜索到3个配置文件，请确认是否无多余文件！
['person1.json', 'config.json', 'person2.json']
2022-08-22T00:35:27 INFO 正在执行person1.json
2022-08-22T00:35:27 INFO Config加载完毕
2022-08-22T00:35:27 INFO 正在获取任务列表
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 86, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/sync.py", line 85, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 99] Address not available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 76, in <module>
    main_multi(autorun)
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 43, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 43, in main
    bbs = mihoyobbs.Mihoyobbs()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/mihoyobbs.py", line 40, in __init__
    self.get_tasks_list()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/mihoyobbs.py", line 56, in get_tasks_list
    req = http.get(url=setting.bbs_Tasks_list, headers=self.headers)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1039, in get
    return self.request(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 902, in send
    response = self._send_handling_auth(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 99] Address not available

## 执行结束... 2022-08-22 00:39:43 耗时 257 秒

**Comment by Womsxd** [comment]
连接超时了好像，国内还是国外？

**Comment by needquit** [comment]
> 连接超时了好像，国内还是国外？

重启了下openwrt，就能正常使用了，我也没搞太清楚
