### ISSUE TITLE
青龙更新后运行显示缺依赖？

### ISSUE THREAD

**Issue by fuhuo8** [Womsxd/AutoMihoyoBBS#215]
求助：没更新时是正常运行的，更新后缺yaml   我已经安装了YAML也显示缺。

## 开始执行... 2022-08-26 09:37:31

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main_multi.py", line 3, in <module>
    import main
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 3, in <module>
    import push
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/push.py", line 10, in <module>
    from config import update_config_need
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/config.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by fuhuo8** [comment]
找到原因了，居然要是pyyaml

**Comment by libmelo** [comment]
> 找到原因了，居然要是pyyaml

确实，更新了首页没有说明。这种更新应该慎重一点的

**Comment by Womsxd** [comment]
这里确实，不过切换yaml实际上算是早有预谋了，为了解决ua相关的问题，加上之前遇到的json格式的配置出现的换行符问题，我最近也是才下定决心切换到yaml做为主配置格式

**Comment by Womsxd** [comment]
readme加入了提示了
