### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Astlm** [Womsxd/AutoMihoyoBBS#223]
第一个
2022-08-28T13:35:19 INFO 触发验证码，即将进行第1次重试，最多3次
2022-08-28T13:35:29 INFO 触发验证码，即将进行第2次重试，最多3次
2022-08-28T13:35:40 INFO 触发验证码，即将进行第3次重试，最多3次
Traceback (most recent call last):
  File "/etc/AutoMihoyoBBS-1/main_multi.py", line 87, in <module>
    main_multi(autorun)
  File "/etc/AutoMihoyoBBS-1/main_multi.py", line 54, in main_multi
    run_code, run_message = main.main()
  File "/etc/AutoMihoyoBBS-1/main.py", line 93, in main
    genshin_message = genshin_help.sign_account()
  File "/etc/AutoMihoyoBBS-1/genshin.py", line 80, in sign_account
    req = self.check_in(i)
  File "/etc/AutoMihoyoBBS-1/genshin.py", line 52, in check_in
    data = req.json()
  File "/usr/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
第二个
2022-08-28T13:41:59 INFO 触发验证码，即将进行第1次重试，最多3次
Traceback (most recent call last):
  File "/etc/AutoMihoyoBBS/main_multi.py", line 87, in <module>
    main_multi(autorun)
  File "/etc/AutoMihoyoBBS/main_multi.py", line 54, in main_multi
    run_code, run_message = main.main()
  File "/etc/AutoMihoyoBBS/main.py", line 93, in main
    genshin_message = genshin_help.sign_account()
  File "/etc/AutoMihoyoBBS/genshin.py", line 80, in sign_account
    req = self.check_in(i)
  File "/etc/AutoMihoyoBBS/genshin.py", line 52, in check_in
    data = req.json()
  File "/usr/lib/python3.10/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by a394862759** [comment]
遇到同样的问题        触发验证码，即将进行第1次重试，最多3次

**Comment by mhy9989** [comment]
我也是同样问题，等待修复

**Comment by Womsxd** [comment]
验证码问题无解

**Comment by Astlm** [comment]
> 验证码问题无解

不是验证码呀 不应该继续执行下一个配置文件吗 他直接报错了 而且是随机的 时有时无

**Comment by Astlm** [comment]
> 验证码问题无解

而且第二个报错只进行了一次重试

**Comment by Womsxd** [comment]
看样子是 #217 同一个问题，我处理一下吧

**Comment by Womsxd** [comment]
合并进入 #217
