### ISSUE TITLE
云原神签到

### ISSUE THREAD

**Issue by afasdaws** [Womsxd/AutoMihoyoBBS#231]
填入抓包获取的token后试运行，返回结果：
Traceback (most recent call last):
  File "D:\桌面\AutoMihoyoBBS-master\main_multi.py", line 87, in <module>
    main_multi(autorun)
  File "D:\桌面\AutoMihoyoBBS-master\main_multi.py", line 54, in main_multi
    run_code, run_message = main.main()
  File "D:\桌面\AutoMihoyoBBS-master\main.py", line 105, in main
    data = cloud_ys.sign_account()
  File "D:\桌面\AutoMihoyoBBS-master\cloud_genshin.py", line 32, in sign_account
    if req["data"]["free_time"]['free_time'] == '0':
TypeError: 'Response' object is not subscriptable

**Comment by clover1420** [comment]
这是判断的变量用错了，把req["data"]["free_time"]['free_time']改成data["data"]["free_time"]['free_time']就行了

**Comment by Womsxd** [comment]
> 这是判断的变量用错了，把req["data"]["free_time"]['free_time']改成data["data"]["free_time"]['free_time']就行了

可以直接让拉取最新版解决了(
