### ISSUE TITLE
运行时经常timeout

### ISSUE THREAD

**Issue by xANoyU** [Womsxd/AutoMihoyoBBS#25]
`2021-10-15T11:56:41 INFO 点赞：Xdm，我想戒崩3了 成功
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\httpx\_transports\default.py", line 61, in map_httpcore_exceptions
    yield
  File "C:\Program Files\python\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Program Files\python\lib\site-packages\httpcore\_sync\connection_pool.py", line 234, in handle_request
    response = connection.handle_request(
  File "C:\Program Files\python\lib\site-packages\httpcore\_sync\connection.py", line 136, in handle_request
    self.socket = self._open_socket(timeout)
  File "C:\Program Files\python\lib\site-packages\httpcore\_sync\connection.py", line 163, in _open_socket
    return self._backend.open_tcp_stream(
  File "C:\Program Files\python\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Program Files\python\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files\python\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_multi.py", line 46, in <module>
    main_multi(autorun)
  File "main_multi.py", line 37, in main_multi
    main.main()
  File "C:\Software\AutoMihoyoBBS\xxx\main.py", line 49, in main
    bbs.Likeposts()
  File "C:\Software\AutoMihoyoBBS\xxx\mihoyobbs.py", line 109, in Likeposts
    req = http.post(url=setting.bbs_Likeurl, headers=self.headers,
  File "C:\Program Files\python\lib\site-packages\httpx\_api.py", line 304, in post
    return request(
  File "C:\Program Files\python\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Program Files\python\lib\site-packages\httpx\_client.py", line 787, in request
    return self.send(
  File "C:\Program Files\python\lib\site-packages\httpx\_client.py", line 878, in send
    response = self._send_handling_auth(
  File "C:\Program Files\python\lib\site-packages\httpx\_client.py", line 908, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Program Files\python\lib\site-packages\httpx\_client.py", line 947, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Program Files\python\lib\site-packages\httpx\_client.py", line 983, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "C:\Program Files\python\lib\site-packages\httpx\_transports\default.py", line 180, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "C:\Program Files\python\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files\python\lib\site-packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out`

`2021-10-15T12:04:40 INFO 正在进行原神签到
2021-10-15T12:04:40 INFO 正在获取米哈游账号绑定原神账号列表...
2021-10-15T12:04:40 INFO 已获取到1个原神账号信息
2021-10-15T12:04:40 INFO 正在获取签到奖励列表...
2021-10-15T12:04:41 INFO 正在为旅行者xxxx进行签到...
2021-10-15T12:04:47 WARNING 获取账号签到信息失败！
`

rt 是因为网络问题还是怎么了

![image](https://user-images.githubusercontent.com/62326160/137432014-751e2ade-7021-4e5b-b249-dbebc2de8cbd.png)
而且cookie失效的好快

**Comment by Womsxd** [comment]
网络错误你可以先多执行一次脚本解决，关于Cookies失效速度的问题，正常来说不可能2-3day就GG

**Comment by Womsxd** [comment]
> cookie的问题不知道怎么回事 刚抓了不久就提示失效了 现在在用别的脚本了😂😂

按道理进隐身/无痕模式抓的不可能1天就失效，只要是在这个模式抓的，基本上都是处于只要不改密码就不会失效的阶段，改手机都没失效

**Comment by sola97** [comment]
我也遇到timeout了，可以改request.py然后增加重试机制
```
import requests
from requests.adapters import HTTPAdapter

http = requests.Session()
adapter = HTTPAdapter(max_retries=3)
http.mount('http://', adapter)
http.mount('https://', adapter)
```
