### ISSUE TITLE
最新版本 docker 运行报错

### ISSUE THREAD

**Issue by Xav1erSue** [Womsxd/AutoMihoyoBBS#300]
单用户，只有一个config.yaml

控制台报错如下
```
mihoyo-bbs_1  | 2022-11-04T14:03:01 INFO Current running datetime: 2022-11-04 14:03:01
mihoyo-bbs_1  | 2022-11-04T14:03:01 INFO Next run datetime: 2022-11-05 09:30:27
mihoyo-bbs_1  | 2022-11-04T14:11:53 INFO 使用DOCKER运行米游社签到
mihoyo-bbs_1  | 2022-11-04T14:11:53 INFO Starting signing
mihoyo-bbs_1  | Traceback (most recent call last):
mihoyo-bbs_1  |   File "/var/app/./main_multi.py", line 3, in <module>
mihoyo-bbs_1  |     import main
mihoyo-bbs_1  |   File "/var/app/main.py", line 3, in <module>
mihoyo-bbs_1  |     import push
mihoyo-bbs_1  |   File "/var/app/push.py", line 9, in <module>
mihoyo-bbs_1  |     import config
mihoyo-bbs_1  |   File "/var/app/config.py", line 2, in <module>
mihoyo-bbs_1  |     import yaml
mihoyo-bbs_1  | ModuleNotFoundError: No module named 'yaml'
mihoyo-bbs_1  | 2022-11-04T14:11:53 INFO Current running datetime: 2022-11-04 14:11:53
mihoyo-bbs_1  | 2022-11-04T14:11:53 INFO Next run datetime: 2022-11-05 09:30:05
```

**Comment by Womsxd** [comment]
尝试重新拉取镜像看看？

**Comment by Xav1erSue** [comment]
> 尝试重新拉取镜像看看？

可以啦
