### ISSUE TITLE
希望能支持下青龙面板

### ISSUE THREAD

**Issue by qiu-lzsnmb** [Womsxd/AutoMihoyoBBS#33]

**Comment by Womsxd** [comment]
这玩意用不着我这边支持吧，我这边只要是个能运行python3+定时执行的环境就能跑了

**Comment by Womsxd** [comment]
![image](https://user-images.githubusercontent.com/45663319/140746247-2e11f27b-fd67-4215-883a-fe067c8cf725.png)
这个你看情况吧，我自己也没用过，主要还是命令看不懂这玩意怎么玩

**Comment by Womsxd** [comment]
ql repo https://github.com/Womsxd/AutoMihoyoBBS "*"

**Comment by qiu-lzsnmb** [comment]
直接一键拉库，自动更新，方便很多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月8日(周一) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Womsxd/AutoMihoyoBBS] 希望能支持下青龙面板 (Issue #33)




 
这玩意用不着我这边支持吧，我这边只要是个能运行python3+定时执行的环境就能跑了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SouthernDreamS6** [comment]
ql repo https://github.com/Womsxd/AutoMihoyoBBS.git
然后自己创建config文件夹和里面的文件吧
青龙这玩意我也玩没太懂

**Comment by SouthernDreamS6** [comment]
手动注释main_multi.py第31-34行
然后设置青龙定时任务

**Comment by SouthernDreamS6** [comment]
编辑定时
名称
米游社多用户
命令
task Womsxd_AutoMihoyoBBS/main_multi.py
定时规则
0 9 * * *

**Comment by SouthernDreamS6** [comment]
下面是我的运行日志
我一共有两个账号
有一个账号提示 WARNING Config未启用
然后不跑任务
请问这是什么原因呀

——————以下为青龙输出的日志——————
—————部分设计隐私的内容已修改—————

日志-米游社多用户
## 开始执行... 2021-11-28 19:28:15

2021-11-28T19:28:16 INFO AutoMihoyoBBS Multi User mode
2021-11-28T19:28:16 INFO 正在搜索配置文件！
2021-11-28T19:28:16 INFO 已搜索到2个配置文件，请确认是否无多余文件！
['账号1.json', '账号2.json']
2021-11-28T19:28:16 INFO 正在执行账号1.json
2021-11-28T19:28:16 INFO Config加载完毕
2021-11-28T19:28:16 WARNING Config未启用！
2021-11-28T19:28:16 INFO 账号1.json执行完毕
2021-11-28T19:28:24 INFO 正在执行账号2.json
2021-11-28T19:28:24 INFO Config加载完毕
2021-11-28T19:28:24 INFO 正在获取任务列表
2021-11-28T19:28:24 INFO 今天已经全部完成了！一共获得90个米游币，目前有380个米游币
2021-11-28T19:28:24 INFO 正在进行原神签到
2021-11-28T19:28:24 INFO 正在获取米哈游账号绑定原神账号列表...
2021-11-28T19:28:25 INFO 已获取到1个原神账号信息
2021-11-28T19:28:25 INFO 正在获取签到奖励列表...
2021-11-28T19:28:25 INFO 正在为旅行者账号2xxx进行签到...
2021-11-28T19:28:33 INFO 旅行者账号2xxx今天已经签到过了~
今天获得的奖励是冒险家的经验x3
2021-11-28T19:28:35 INFO 崩坏3签到功能未启用！
2021-11-28T19:28:35 INFO 账号2.json执行完毕

## 执行结束... 2021-11-28 19:28:40 耗时 25 秒

**Comment by Womsxd** [comment]
> main_multi.py

task Womsxd_AutoMihoyoBBS/main_multi.py autorun

可以这样子执行吗？

**Comment by SouthernDreamS6** [comment]
task后面跟脚本路径

**Comment by SouthernDreamS6** [comment]
task就是工作
青龙的task+路径就是让指定脚本运行的意思
配合cron达到一个定时工作的效果

**Comment by Womsxd** [comment]
> task就是工作 青龙的task+路径就是让指定脚本运行的意思 配合cron达到一个定时工作的效果

那有啥环境可以检测到青龙么，我可以做一下优化

**Comment by ankokucao** [comment]
我用控制台抓取的cookies怎么缺少login_ticket这个字段，运行提示：
`cookie中没有'login_ticket'字段,请重新登录米游社，重新抓取cookie!`

**Comment by ankokucao** [comment]
也有可能是米哈游改了

**Comment by Womsxd** [comment]
> 也有可能是米哈游改了

你操作问题，请仔细阅读readme

**Comment by Womsxd** [comment]
> 手动注释main_multi.py第31-34行 然后设置青龙定时任务

可以不用删了，添加一个环境变量 AutoMihoyoBBS_autorun 设置为1就可以了

**Comment by SNAKEXGC** [comment]
支持青龙的，但是要你有动手能力，我就是青龙跑的

**Comment by Womsxd** [comment]
> 支持青龙的，但是要你有动手能力，我就是青龙跑的

回复一下这条吧：用其他工具的时候，比如青龙如果要按enter就不能正常进行，希望如果按enter不是必须的话，能否考虑移除一下，感谢大佬提供的这么好的项目！！！大佬辛苦了！
可以设置环境变量AutoMihoyoBBS_autorun并且设置为1就行了

**Comment by SNAKEXGC** [comment]
> 
好的，谢谢大佬

**Comment by jjjyyyllll** [comment]
> AutoMihoyoBBS_autorun

部署到青龙了  推送怎么整？？ 貌似收不到push或者server酱的推送？

**Comment by SouthernDreamS6** [comment]
可以参考一下
我用了两种推流方法
第一种是青龙的sendNotify.js文件
第二种是onebot机器人直接读取日志文件发送消息

**Comment by SouthernDreamS6** [comment]
@jjjyyyllll 我用了两种推送方法，可以参考下

第一种是青龙自带的sendNotify.js文件定时推送

第二种是通过onebot，在日志文件种切出需要的内容发送
onebot同时对接了Q和V，在发送指令的时候推送日志

**Comment by jjjyyyllll** [comment]
> @jjjyyyllll 我用了两种推送方法，可以参考下
> 
> 第一种是青龙自带的sendNotify.js文件定时推送
> 
> 第二种是通过onebot，在日志文件种切出需要的内容发送 onebot同时对接了Q和V，在发送指令的时候推送日志

用青龙自带的sendNotify.js推送 直接配置Womsxd_AutoMihoyoBBS的sendNotify.js就可以了？  貌似配置了没效果？

**Comment by SouthernDreamS6** [comment]
> 

我2.11.3的青龙拉进去就自动配置了推送

**Comment by tanmx** [comment]
```
2022-04-26T10:49:54 INFO 正在执行推送......
2022-04-26T10:49:54 WARNING Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bd79f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
2022-04-26T10:49:54 WARNING Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
2022-04-26T10:49:54 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f2e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
2022-04-26T10:49:54 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
2022-04-26T10:49:54 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f700>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /send_private_msg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 98, in <module>
    push.push(status_code, message)
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/push.py", line 110, in push
    eval(push_server[:10].lower() + "(status, push_message)")
  File "<string>", line 1, in <module>
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/push.py", line 63, in cqhttp
    http.post(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /send_private_msg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused'))

## 执行结束... 2022-04-26 10:49:54 耗时 18 秒
```

**Comment by Womsxd** [comment]
> ```
> 2022-04-26T10:49:54 INFO 正在执行推送......
> 2022-04-26T10:49:54 WARNING Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bd79f10>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
> 2022-04-26T10:49:54 WARNING Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f0d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
> 2022-04-26T10:49:54 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f2e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
> 2022-04-26T10:49:54 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f4f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
> 2022-04-26T10:49:54 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f700>: Failed to establish a new connection: [Errno 111] Connection refused')': /send_private_msg
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
>     raise err
>   File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/usr/lib/python3.9/http/client.py", line 1279, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.9/http/client.py", line 974, in send
>     self.connect()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
>     return self.urlopen(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
>     return self.urlopen(
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 783, in urlopen
>     return self.urlopen(
>   [Previous line repeated 2 more times]
>   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /send_private_msg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 98, in <module>
>     push.push(status_code, message)
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/push.py", line 110, in push
>     eval(push_server[:10].lower() + "(status, push_message)")
>   File "<string>", line 1, in <module>
>   File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/push.py", line 63, in cqhttp
>     http.post(
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /send_private_msg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8bb6f910>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> ## 执行结束... 2022-04-26 10:49:54 耗时 18 秒
> ```

你push.ini的问题，不是项目的Bug

**Comment by tanmx** [comment]
@Womsxd 谢谢 我配置错了
