### ISSUE TITLE
青龙面板一直卡在获取任务列表

### ISSUE THREAD

**Issue by ZZH731019** [Womsxd/AutoMihoyoBBS#337]
![mmexport1674799449243.png](https://user-images.githubusercontent.com/100362620/215020291-d19f594a-f6d1-4009-821d-cf42a297cc80.png)

**Comment by ZZH731019** [comment]
## 开始执行... 2023-01-27 14:27:57

2023-01-27T14:27:58 INFO Config加载完毕
2023-01-27T14:27:58 INFO 正在获取任务列表
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_excepti

**Comment by YYY-919** [comment]
网络问题吧，试试魔法工具

**Comment by ZZH731019** [comment]
> 网络问题吧，试试魔法工具

服务器还能挂工具吗

**Comment by YYY-919** [comment]
> > 网络问题吧，试试魔法工具
> 
> 服务器还能挂工具吗

v2rayA吧，不过在这个项目上面没试过

**Comment by ZZH731019** [comment]
我换服务器了，换服务器就好了
