### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by QiE2035** [Womsxd/AutoMihoyoBBS#56]
2022-01-30T18:08:49 INFO Config加载完毕
2022-01-30T18:08:49 INFO 正在获取任务列表
2022-01-30T18:08:50 INFO 新的一天，今天可以获得110个米游币
2022-01-30T18:08:50 INFO 正在获取帖子列表......
2022-01-30T18:08:51 INFO 已获取5个帖子
2022-01-30T18:08:51 INFO 正在签到......
2022-01-30T18:08:51 INFO 大别野OK
2022-01-30T18:08:59 INFO 崩坏3OK
2022-01-30T18:09:01 INFO 崩坏：星穹铁道OK
2022-01-30T18:09:11 INFO 原神OK
2022-01-30T18:09:19 INFO 崩坏2OK
2022-01-30T18:09:27 INFO 未定事件簿OK
2022-01-30T18:09:29 INFO 正在看帖......
2022-01-30T18:09:43 INFO 正在点赞......
2022-01-30T18:10:30 INFO 正在执行分享任务......
2022-01-30T18:10:31 INFO 分享任务执行成功......
2022-01-30T18:10:38 INFO 正在获取任务列表
2022-01-30T18:10:39 INFO 今天已经获得110个米游币，还能获得0个米游币，目前有2660个米游币
2022-01-30T18:10:44 INFO 正在进行原神签到
2022-01-30T18:10:44 INFO 正在获取米哈游账号绑定原神账号列表...
2022-01-30T18:10:45 INFO 已获取到2个原神账号信息
2022-01-30T18:10:45 INFO 正在获取签到奖励列表...
2022-01-30T18:10:45 INFO 正在为旅行者企鹅2035进行签到...
2022-01-30T18:10:53 INFO 旅行者企鹅2035签到成功~
今天获得的奖励是摩拉x5000
2022-01-30T18:10:53 INFO 正在为旅行者玩家199569368进行签到...
2022-01-30T18:11:11 INFO 旅行者玩家199569368签到成功~
今天获得的奖励是摩拉x5000
2022-01-30T18:11:17 INFO 正在进行崩坏3签到
2022-01-30T18:11:17 INFO 正在获取米哈游账号绑定的崩坏3账号列表...
2022-01-30T18:11:18 INFO 已获取到2个崩坏3账号信息
2022-01-30T18:11:18 INFO 正在为舰长企鹅2035进行签到...
2022-01-30T18:11:29 INFO 舰长企鹅2035签到成功~
今天获得的奖励是金币x35000
2022-01-30T18:11:29 INFO 正在为舰长企鹅2035进行签到...
2022-01-30T18:11:40 INFO 舰长企鹅2035签到成功~
今天获得的奖励是金币x35000
Traceback (most recent call last):
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 86, in <module>
    status_code, message = main()
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 75, in main
    return_data += "\n\n" + honkai3rd_help.sign_account()
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/honkai3rd.py", line 100, in sign_account
    if is_data["is_sign"] or data["retcode"] == 0 or data["retcode"] == -5003:
TypeError: 'bool' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by QiE2035** [comment]
2022-01-30T18:08:49 INFO Config加载完毕
2022-01-30T18:08:49 INFO 正在获取任务列表
2022-01-30T18:08:50 INFO 新的一天，今天可以获得110个米游币
2022-01-30T18:08:50 INFO 正在获取帖子列表......
2022-01-30T18:08:51 INFO 已获取5个帖子
2022-01-30T18:08:51 INFO 正在签到......
2022-01-30T18:08:51 INFO 大别野OK
2022-01-30T18:08:59 INFO 崩坏3OK
2022-01-30T18:09:01 INFO 崩坏：星穹铁道OK
2022-01-30T18:09:11 INFO 原神OK
2022-01-30T18:09:19 INFO 崩坏2OK
2022-01-30T18:09:27 INFO 未定事件簿OK
2022-01-30T18:09:29 INFO 正在看帖......
2022-01-30T18:09:43 INFO 正在点赞......
2022-01-30T18:10:30 INFO 正在执行分享任务......
2022-01-30T18:10:31 INFO 分享任务执行成功......
2022-01-30T18:10:38 INFO 正在获取任务列表
2022-01-30T18:10:39 INFO 今天已经获得110个米游币，还能获得0个米游币，目前有2660个米游币
2022-01-30T18:10:44 INFO 正在进行原神签到
2022-01-30T18:10:44 INFO 正在获取米哈游账号绑定原神账号列表...
2022-01-30T18:10:45 INFO 已获取到2个原神账号信息
2022-01-30T18:10:45 INFO 正在获取签到奖励列表...
2022-01-30T18:10:45 INFO 正在为旅行者企鹅2035进行签到...
2022-01-30T18:10:53 INFO 旅行者企鹅2035签到成功~
今天获得的奖励是摩拉x5000
2022-01-30T18:10:53 INFO 正在为旅行者玩家199569368进行签到...
2022-01-30T18:11:11 INFO 旅行者玩家199569368签到成功~
今天获得的奖励是摩拉x5000
2022-01-30T18:11:17 INFO 正在进行崩坏3签到
2022-01-30T18:11:17 INFO 正在获取米哈游账号绑定的崩坏3账号列表...
2022-01-30T18:11:18 INFO 已获取到2个崩坏3账号信息
2022-01-30T18:11:18 INFO 正在为舰长企鹅2035进行签到...
2022-01-30T18:11:29 INFO 舰长企鹅2035签到成功~
今天获得的奖励是金币x35000
2022-01-30T18:11:29 INFO 正在为舰长企鹅2035进行签到...
2022-01-30T18:11:40 INFO 舰长企鹅2035签到成功~
今天获得的奖励是金币x35000
Traceback (most recent call last):
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 86, in <module>
    status_code, message = main()
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/main.py", line 75, in main
    return_data += "\n\n" + honkai3rd_help.sign_account()
  File "/home/runner/work/AutoMihoyoBBS_Runner/AutoMihoyoBBS_Runner/AutoMihoyoBBS/honkai3rd.py", line 100, in sign_account
    if is_data["is_sign"] or data["retcode"] == 0 or data["retcode"] == -5003:
TypeError: 'bool' object is not subscriptable
Error: Process completed with exit code 1.

**Comment by Womsxd** [comment]
已更新修复，请拉取最新代码
