### ISSUE TITLE
签到失败了，查了一下好像是代码问题，没懂

### ISSUE THREAD

**Issue by kmzs123** [Womsxd/AutoMihoyoBBS#60]
已经完全按照readme的方法获取了Cookie
下面是log
```
kmzs@debian:~/AutoMihoyoBBS$ python3 main.py
2022-02-08T00:51:08 INFO Config加载完毕
2022-02-08T00:51:08 INFO 正在获取任务列表
2022-02-08T00:51:09 INFO 今天已经全部完成了！一共获得110个米游币，目前有16750个米游币
2022-02-08T00:51:09 INFO 正在进行原神签到
2022-02-08T00:51:09 INFO 正在获取米哈游账号绑定原神账号列表...
2022-02-08T00:51:10 INFO 已获取到2个原神账号信息
2022-02-08T00:51:10 INFO 正在获取签到奖励列表...
2022-02-08T00:51:10 INFO 正在为旅行者空の竹くん进行签到...
2022-02-08T00:51:19 INFO 旅行者XXXXX今天已经签到过了~
今天获得的奖励是冒险家的经验x3
Traceback (most recent call last):
  File "/home/kmzs/AutoMihoyoBBS/main.py", line 86, in <module>
    status_code, message = main()
  File "/home/kmzs/AutoMihoyoBBS/main.py", line 67, in main
    return_data += "\n\n" + genshin_help.sign_account()
  File "/home/kmzs/AutoMihoyoBBS/genshin.py", line 100, in sign_account
    if data["retcode"] == 0:
UnboundLocalError: local variable 'data' referenced before assignment
````
系统：Debian11
版本：Python 3.9.2
~~我之前(2021-11-05 10:52:40)在腾讯里部署的还能正常运行，想更新一下结果就出问题了~~

**Comment by stkevintan** [comment]
重复签到就会触发这个bug，实际上应该不会影响正常签到。
