### ISSUE TITLE
多用户腾讯云函数执行出错

### ISSUE THREAD

**Issue by DarkKnightReturn** [Womsxd/AutoMihoyoBBS#76]
我之前一个用户用着没问题，现在加了一个之后就成这样了
 START RequestId: 2be7ae30-0073-48e7-ae90-99394ff913d4
ERROR RequestId: 2be7ae30-0073-48e7-ae90-99394ff913d4 Result: Traceback (most recent call last):   File "/var/user/index.py", line 6, in main_handler     main.main()   File "/var/user/main.py", line 16, in main     config.load_config()   File "/var/user/config.py", line 45, in load_config     with open(config_Path, "r") as f: FileNotFoundError: [Errno 2] No such file or directory: '/var/user/config/config.json'
END RequestId: 2be7ae30-0073-48e7-ae90-99394ff913d4
Report RequestId: 2be7ae30-0073-48e7-ae90-99394ff913d4 Duration: 1ms Memory: 128MB MemUsage: 16.50MB
是因为我的文件不叫config.json的问题吗？求助大佬(＞﹏＜)

**Comment by DarkKnightReturn** [comment]
我看index之后明白了，需要把调用方法改成index.main_handler_mulit来执行多用户
