### ISSUE TITLE
青龙面板

### ISSUE THREAD

**Issue by Unicorni** [Womsxd/AutoMihoyoBBS#77]
青龙面板安装[AutoMihoyoBBS](https://github.com/Womsxd/AutoMihoyoBBS)，希望作者给一个详细的安装教程，在那个安装简介里给个方案。我的青龙面板总报一些错误，安装不上。那个config.json,创建在 青龙 脚本管理》Womsxd_AutoMihoyoBBS》创建config.json文件下？ ，还有你们得到的米优社 Cookiees是几位的？40位的？ 随机数字   谢谢Womsxd作者

**Comment by Unicorni** [comment]
日志-米游社单用户
## 开始执行... 2022-04-12 16:51:18

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 86, in <module>
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 17, in main
    config.load_config()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/config.py", line 45, in load_config
    with open(config_Path, "r") as f:
NotADirectoryError: [Errno 20] Not a directory: '/ql/data/scripts/Womsxd_AutoMihoyoBBS/config/config.json'

## 执行结束... 2022-04-12 16:51:39 耗时 21 秒

**Comment by Unicorni** [comment]
https://www.kejiwanjia.com/jiaocheng/46595.html/comment-page-13#comment

**Comment by Womsxd** [comment]
配置文件塞这里
/ql/data/scripts/Womsxd_AutoMihoyoBBS/config/
单用户的配置文件的路径
/ql/data/scripts/Womsxd_AutoMihoyoBBS/config/config.json

**Comment by wxhwz** [comment]
我是docker的青龙，一样的问题，
docker exec -it qinglong bash
cd /ql/data/scripts/Womsxd_AutoMihoyoBBS/
看看目录下有没config文件夹，没有的话需要手动创建并复制config.json

**Comment by MoXiaoXi233** [comment]
我写了一个比较易懂的教程https://note.moxiify.cn/post/AutoMihoyoBBS

**Comment by Lemonmous** [comment]
> 我写了一个比较易懂的教程https://note.moxiify.cn/post/AutoMihoyoBBS

你好想请问一下设置了推送信息没推送咋解决

**Comment by libmelo** [comment]
> 我写了一个比较易懂的教程https://note.moxiify.cn/post/AutoMihoyoBBS

你的教程写得很好，比较详细，但个人觉得有一点建议（部分需要作者方面的修改）
因为我们使用qinglong，一方面是看中它集中管理定时任务的功能，另一方面也是看中它可以定时更新脚本（以免脚本失效），所以可以设置qinglong的拉库命令定时启动（更新）
另一方面，一般cookie是有时效的，也就是失效后需要我们更新，qinglong目前的做法是将cookie写成环境变量方便修改，如果能在后面的更新版本里加入对应的环境变量的支持就好了（可以支持多账户），这一修改可能需要config部分的重构
最后，可能是qinglong用得不熟，百思不得其解，qinglong拉库无法保留config目录，看了几个教程也是需要自行创建config目录，但是我其它的脚本是可以拉回目录的。因为qinglong面板对文件支持还不错，比如修改新增config.json还算方便，但是对目录支持很差（无法创建和删除）。这个问题希望探讨一下

**Comment by muzi13** [comment]
> 我写了一个比较易懂的教程https://note.moxiify.cn/post/AutoMihoyoBBS

使用此方法可行（只尝试了单账号），感谢！
目前需要更新的地方：
① ql/data/scripts/Womsxd_AutoMihoyoBBS/config目录下的config.json改为comfig.yaml
② 新增依赖PyYAML

**Comment by RELemon** [comment]
2022/10/05测试：用部署在我软路由上的青龙面板能正常运行脚本，就是不知道还会不会继续提示验证码，明天看一下。

![image](https://user-images.githubusercontent.com/112569977/193904510-62b21043-cc86-4ba6-938e-2c06747b82e6.png)
