### ISSUE TITLE
docker部署后启动失败

### ISSUE THREAD

**Issue by djxyy5505** [Womsxd/AutoMihoyoBBS#80]
Traceback (most recent call last):
  File "/var/app/./main_multi.py", line 65, in 
    main_multi(autorun)
  File "/var/app/./main_multi.py", line 43, in main_multi
    run_code, run_message = main.main()
  File "/var/app/main.py", line 17, in main
    config.load_config()
  File "/var/app/config.py", line 45, in load_config
    with open(config_Path, "r") as f:
PermissionError: [Errno 13] Permission denied: '/var/app/config/aaa.json'
2022-04-16T00:34:12 INFO Current running datetime: 2022-04-16 00:34:12

大佬，我部署到docker后，运行提示这个错误

**Comment by Darkatse** [comment]
你好，我是Docker方面的维护者。Permission denied是容器内部权限错误，你可以先临时在主机上用`chmod -R 777 ./config/`解决，稍后我会尝试更新一下Docker镜像解决一下这个问题
~~很奇怪，我本地测试时候没出现这个问题，刚刚试了一下成功复现了~~

**Comment by djxyy5505** [comment]
> 你好，我是 Docker 方面的维护者。Permission denied 是包含权限错误，你可以先在主机上`chmod -R 777 ./config/`使用解决，稍后我会尝试更新一下Docker镜像解决这个问题 ~很平均，我在本地测试的时候没有出现这个问题，刚刚试了一下成功复现了~

您好，我在本地Linux部署了，运行成功了。然后再使用了docker-compose up -d构建docker，并成功运行了。我想可能是的docker没有requirements.txt模块的原因。
