### ISSUE TITLE
获取任务列表失败，你的cookie可能已过期，请重新设置cookie

### ISSUE THREAD

**Issue by Teconheci** [Womsxd/AutoMihoyoBBS#87]
我在尝试多账号时，第二个账号获取cookie时忘记用无痕模式，执行后，再次按步骤来执行，执行单账户显示

Config加载完毕

正在获取任务列表

https://bbs-api.mihoyo.com:443 "GET /apihub/sapi/getUserMissionsState HTTP/1.1" 200 71

获取任务列表失败，你的cookie可能已过期，请重新设置cookie。

ERROR RequestId: 5a7e347c-aac4-4e33-a162-7a6ffce93404 Result: Traceback (most recent call last):   File "/var/user/index.py", line 9, in main_handler     status_code, push_message = main.main()   File "/var/user/main.py", line 39, in main     bbs = mihoyobbs.Mihoyobbs()   File "/var/user/mihoyobbs.py", line 39, in __init__     self.get_tasks_list()   File "/var/user/mihoyobbs.py", line 59, in get_tasks_list     config.clear_cookies()   File "/var/user/config.py", line 83, in clear_cookies     with open(config_Path, "r+") as f: OSError: [Errno 30] Read-only file system: '/var/user/config/config.json'

END RequestId: 5a7e347c-aac4-4e33-a162-7a6ffce93404

Report RequestId: 5a7e347c-aac4-4e33-a162-7a6ffce93404 Duration: 69ms Memory: 128MB MemUsage: 17.12MB

**Comment by Teconheci** [comment]
再次执行后显示
2022-04-23T23:10:00 INFO Config加载完毕
2022-04-23T23:10:00 WARNING Config未启用！

**Comment by Teconheci** [comment]
额。从之前的步骤又走了一遍，没问题了
